### ISSUE TITLE
error function evaluate ?

### ISSUE THREAD

**Issue by clmauc** [sioufia/health_data_challenge#3]
https://github.com/sioufia/health_data_challenge/blob/edbe310bd5de310a58c65239ffccf07c864c978c/eval.py#L87

@sioufia Je pense que ça devrait être ça plutôt non ? ;)  : 

global_score = (f1_concept + f1_assertion + f1_rel) / 3 

et pour les fonctions "classification_report" et "confusion_matrix" il faut spécifier labels = sorted_labels

**Comment by sioufia** [comment]
Merci, c'est corrigé !
